-- *******************************************
-- 1. DROP SCHEMA
-- *******************************************

DROP SCHEMA IF EXISTS CORE CASCADE;

-- *******************************************
-- 2. CREATE SCHEMA CORE
-- *******************************************

CREATE SCHEMA CORE;

CREATE TABLE CORE.ACTION_LOG_TYPE (
    ACTION_LOG_TYPE_ID SERIAL NOT NULL,
    ACTION_LOG_TYPE_NAME VARCHAR(100) NOT NULL,
    CONSTRAINT PK_ACTION_LOG_TYPE PRIMARY KEY (ACTION_LOG_TYPE_ID),
    CONSTRAINT UK_ACTION_LOG_TYPE_01 UNIQUE (ACTION_LOG_TYPE_NAME)
);

CREATE TABLE CORE.USER (
    USER_ID UUID NOT NULL,
    USER_NAME VARCHAR(254) NOT NULL,
    USER_NIF CHAR(9) NOT NULL,
    USER_EMAIL VARCHAR(254) NOT NULL,
    USER_PASSWORD_HASH TEXT NOT NULL,
    USER_IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UK_USER_01_NIF UNIQUE (USER_NIF),
    CONSTRAINT UK_USER_02_EMAIL UNIQUE (USER_EMAIL)
);

CREATE TABLE CORE.CLIENT (
    CLIENT_ID UUID NOT NULL,
    CLIENT_ADDRESS VARCHAR(500) NOT NULL,
    CONSTRAINT PK_CLIENT PRIMARY KEY (CLIENT_ID),
    CONSTRAINT FK_CLIENT_USER_01 FOREIGN KEY (CLIENT_ID) REFERENCES CORE.USER (USER_ID) ON DELETE CASCADE
);

CREATE TABLE CORE.LAWYER (
    LAWYER_ID UUID NOT NULL,
    LAWYER_PROFESSIONAL_REGISTER VARCHAR(20) NOT NULL,
    CONSTRAINT PK_LAWYER PRIMARY KEY (LAWYER_ID),
    CONSTRAINT UK_LAWYER_01_REGISTER UNIQUE (LAWYER_PROFESSIONAL_REGISTER),
    CONSTRAINT FK_LAWYER_USER_01 FOREIGN KEY (LAWYER_ID) REFERENCES CORE.USER (USER_ID) ON DELETE CASCADE
);

CREATE TABLE CORE.ADMIN (
    ADMIN_ID UUID NOT NULL,
    ADMIN_STARTED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ADMIN PRIMARY KEY (ADMIN_ID),
    CONSTRAINT FK_ADMIN_USER_01 FOREIGN KEY (ADMIN_ID) REFERENCES CORE.USER (USER_ID) ON DELETE CASCADE
);

CREATE TABLE CORE.PHONE (
    PHONE_ID UUID NOT NULL,
    FK_USER_ID UUID NOT NULL,
    PHONE_COUNTRY_CODE SMALLINT NOT NULL DEFAULT 351,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    PHONE_IS_MAIN BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_PHONE PRIMARY KEY (PHONE_ID),
    CONSTRAINT UK_PHONE_01_USER_NUMBER UNIQUE (FK_USER_ID, PHONE_COUNTRY_CODE, PHONE_NUMBER),
    CONSTRAINT FK_PHONE_USER_01 FOREIGN KEY (FK_USER_ID) REFERENCES CORE.USER (USER_ID) ON DELETE RESTRICT
);

CREATE TABLE CORE.USER_LOG (
    USER_LOG_ID UUID NOT NULL,
    AFFECTED_USER_ID UUID,
    UPDATED_BY_ID UUID,
    USER_LOG_UPDATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_LOG_OLD_VALUE JSONB NOT NULL,
    USER_LOG_NEW_VALUE JSONB NOT NULL,
    ACTION_LOG_TYPE_ID INTEGER,
    CONSTRAINT PK_USER_LOG PRIMARY KEY (USER_LOG_ID),
    CONSTRAINT FK_USER_LOG_AFFECTED_USER_01 FOREIGN KEY (AFFECTED_USER_ID) REFERENCES CORE.USER (USER_ID) ON DELETE SET NULL,
    CONSTRAINT FK_USER_LOG_UPDATED_BY_01 FOREIGN KEY (UPDATED_BY_ID) REFERENCES CORE.USER (USER_ID) ON DELETE SET NULL
);

-- *******************************************
-- 3. INDEXES
-- *******************************************

CREATE INDEX IDX_PHONE_FK_USER_ID ON CORE.PHONE (FK_USER_ID);
CREATE INDEX IDX_USER_LOG_AFFECTED_USER_ID ON CORE.USER_LOG (AFFECTED_USER_ID);
CREATE INDEX IDX_USER_LOG_UPDATED_BY_ID ON CORE.USER_LOG (UPDATED_BY_ID);