-- *******************************************
-- 1. DROP SCHEMA
-- *******************************************

DROP SCHEMA IF EXISTS LEGAL CASCADE;

-- *******************************************
-- 2. CREATE SCHEMA LEGAL
-- *******************************************

CREATE SCHEMA LEGAL;

CREATE TABLE LEGAL.PROCESS_TYPE (
    PROCESS_TYPE_ID SERIAL NOT NULL,
    PROCESS_TYPE_NAME VARCHAR(255) NOT NULL,
    PROCESS_TYPE_IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_PROCESS_TYPE PRIMARY KEY (PROCESS_TYPE_ID),
    CONSTRAINT UK_PROCESS_TYPE_01 UNIQUE (PROCESS_TYPE_NAME)
);

CREATE TABLE LEGAL.PROCESS_PHASE (
    PROCESS_PHASE_ID SERIAL NOT NULL,
    PROCESS_PHASE_NAME VARCHAR(255) NOT NULL,
    PROCESS_PHASE_DESCRIPTION TEXT,
    PROCESS_PHASE_IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_PROCESS_PHASE PRIMARY KEY (PROCESS_PHASE_ID),
    CONSTRAINT UK_PROCESS_PHASE_01 UNIQUE (PROCESS_PHASE_NAME)
);

CREATE TABLE LEGAL.PROCESS_STATUS (
    PROCESS_STATUS_ID SERIAL NOT NULL,
    PROCESS_STATUS_NAME VARCHAR(50) NOT NULL,
    PROCESS_STATUS_IS_FINAL BOOLEAN NOT NULL DEFAULT FALSE,
    PROCESS_STATUS_IS_DEFAULT BOOLEAN NOT NULL DEFAULT TRUE,
    PROCESS_STATUS_IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_PROCESS_STATUS PRIMARY KEY (PROCESS_STATUS_ID),
    CONSTRAINT UK_PROCESS_STATUS_01 UNIQUE (PROCESS_STATUS_NAME)
);

CREATE TABLE LEGAL.PROCESS_TYPE_PHASE (
    PROCESS_TYPE_PHASE_ID SERIAL NOT NULL,
    PROCESS_PHASE_ID INTEGER NOT NULL,
    PROCESS_TYPE_ID INTEGER NOT NULL,
    PROCESS_TYPE_PHASE_ORDER SMALLINT NOT NULL,
    PROCESS_TYPE_PHASE_IS_OPTIONAL BOOLEAN NOT NULL DEFAULT FALSE,
    PROCESS_TYPE_PHASE_IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_PROCESS_TYPE_PHASE PRIMARY KEY (PROCESS_TYPE_PHASE_ID),
    CONSTRAINT UK_PROCESS_TYPE_PHASE_01 UNIQUE (PROCESS_TYPE_ID, PROCESS_PHASE_ID),
    CONSTRAINT UK_PROCESS_TYPE_PHASE_02 UNIQUE (PROCESS_TYPE_PHASE_ORDER, PROCESS_TYPE_ID),
    CONSTRAINT FK_PROCESS_TYPE_PHASE_PROCESS_TYPE_01 FOREIGN KEY (PROCESS_TYPE_ID) REFERENCES LEGAL.PROCESS_TYPE (PROCESS_TYPE_ID),
    CONSTRAINT FK_PROCESS_TYPE_PHASE_PROCESS_PHASE_02 FOREIGN KEY (PROCESS_PHASE_ID) REFERENCES LEGAL.PROCESS_PHASE (PROCESS_PHASE_ID)
);

CREATE TABLE LEGAL.PROCESS (
    PROCESS_ID UUID NOT NULL DEFAULT gen_random_uuid(),
    PROCESS_NAME VARCHAR(255) NOT NULL,
    PROCESS_NUMBER VARCHAR(255) NOT NULL,
    CLIENT_ID UUID NOT NULL,
    LAWYER_ID UUID NOT NULL,
    PROCESS_ADVERSE_PART_NAME VARCHAR(255),
    PROCESS_OPPOSING_COUNSEL_NAME VARCHAR(255),
    PROCESS_CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PROCESS_CLOSED_AT TIMESTAMP WITHOUT TIME ZONE,
    PROCESS_DSC TEXT,
    PROCESS_NEXT_HEARING_DATE TIMESTAMP WITHOUT TIME ZONE,
    PROCESS_PRIORITY SMALLINT NOT NULL,
    PROCESS_COURT_INFO TEXT NOT NULL,
    PROCESS_TYPE_PHASE_ID INTEGER NOT NULL,
    PROCESS_STATUS_ID INTEGER NOT NULL,
    CONSTRAINT PK_PROCESS PRIMARY KEY (PROCESS_ID),
    CONSTRAINT UK_PROCESS_01 UNIQUE (PROCESS_NUMBER, CLIENT_ID, LAWYER_ID),
    CONSTRAINT FK_PROCESS_CLIENT_01 FOREIGN KEY (CLIENT_ID) REFERENCES CORE.CLIENT (CLIENT_ID),
    CONSTRAINT FK_PROCESS_LAWYER_02 FOREIGN KEY (LAWYER_ID) REFERENCES CORE.LAWYER (LAWYER_ID),
    CONSTRAINT FK_PROCESS_TYPE_PHASE_04 FOREIGN KEY (PROCESS_TYPE_PHASE_ID) REFERENCES LEGAL.PROCESS_TYPE_PHASE (PROCESS_TYPE_PHASE_ID),
    CONSTRAINT FK_PROCESS_STATUS_03 FOREIGN KEY (PROCESS_STATUS_ID) REFERENCES LEGAL.PROCESS_STATUS (PROCESS_STATUS_ID)
);

CREATE TABLE LEGAL.PROCESS_LOG (
    PROCESS_LOG_ID UUID NOT NULL,
    PROCESS_ID UUID NOT NULL,
    UPDATED_BY UUID NOT NULL,
    UPDATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OLD_VALUE JSONB NOT NULL,
    NEW_VALUE JSONB NOT NULL,
    ACTION_LOG_TYPE_ID INTEGER NOT NULL,
    CONSTRAINT PK_PROCESS_LOG PRIMARY KEY (PROCESS_LOG_ID),
    CONSTRAINT FK_PROCESS_LOG_PROCESS_01 FOREIGN KEY (PROCESS_ID) REFERENCES LEGAL.PROCESS (PROCESS_ID),
    CONSTRAINT FK_PROCESS_LOG_USER_02 FOREIGN KEY (UPDATED_BY) REFERENCES CORE.USER (USER_ID) ON DELETE RESTRICT
);

CREATE TABLE LEGAL.DOCUMENT (
    DOCUMENT_ID UUID NOT NULL DEFAULT gen_random_uuid(),
    PROCESS_ID UUID NOT NULL,
    FILE_NAME VARCHAR(100) NOT NULL,
    FILE BYTEA NOT NULL,
    FILE_MIMETYPE VARCHAR(50) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_DOCUMENT PRIMARY KEY (DOCUMENT_ID),
    CONSTRAINT FK_DOCUMENT_PROCESS_01 FOREIGN KEY (PROCESS_ID) REFERENCES LEGAL.PROCESS (PROCESS_ID) ON DELETE CASCADE
);

CREATE TABLE LEGAL.DOCUMENT_LOG (
    DOCUMENT_LOG_ID UUID NOT NULL DEFAULT gen_random_uuid(),
    DOCUMENT_ID UUID NOT NULL,
    UPDATED_BY UUID NOT NULL,
    ACTION_LOG_TYPE_ID INTEGER NOT NULL,
    UPDATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OLD_VALUE JSONB NOT NULL,
    NEW_VALUE JSONB NOT NULL,
    CONSTRAINT PK_DOCUMENT_LOG PRIMARY KEY (DOCUMENT_LOG_ID),
    CONSTRAINT FK_DOCUMENT_LOG_DOCUMENT_01 FOREIGN KEY (DOCUMENT_ID) REFERENCES LEGAL.DOCUMENT (DOCUMENT_ID),
    CONSTRAINT FK_DOCUMENT_LOG_USER_02 FOREIGN KEY (UPDATED_BY) REFERENCES CORE.USER (USER_ID),
    CONSTRAINT FK_DOCUMENT_LOG_ACTION_TYPE_03 FOREIGN KEY (ACTION_LOG_TYPE_ID) REFERENCES CORE.ACTION_LOG_TYPE (ACTION_LOG_TYPE_ID)
);

-- *******************************************
-- 3. INDEXES
-- *******************************************

CREATE INDEX IDX_DOCUMENT_01 ON LEGAL.DOCUMENT (PROCESS_ID);

CREATE INDEX IDX_DOCUMENT_LOG_01 ON LEGAL.DOCUMENT_LOG (DOCUMENT_ID);
CREATE INDEX IDX_DOCUMENT_LOG_02 ON LEGAL.DOCUMENT_LOG (UPDATED_BY);
CREATE INDEX IDX_DOCUMENT_LOG_03 ON LEGAL.DOCUMENT_LOG (ACTION_LOG_TYPE_ID);

CREATE INDEX IDX_PROCESS_01 ON LEGAL.PROCESS (CLIENT_ID);
CREATE INDEX IDX_PROCESS_02 ON LEGAL.PROCESS (LAWYER_ID);
CREATE INDEX IDX_PROCESS_04 ON LEGAL.PROCESS (PROCESS_TYPE_PHASE_ID);
CREATE INDEX IDX_PROCESS_05 ON LEGAL.PROCESS (PROCESS_STATUS_ID);

CREATE INDEX IDX_PROCESS_LOG_01 ON LEGAL.PROCESS_LOG (PROCESS_ID);
CREATE INDEX IDX_PROCESS_LOG_02 ON LEGAL.PROCESS_LOG (UPDATED_BY);

CREATE INDEX IDX_PROCESS_TYPE_PHASE_01 ON LEGAL.PROCESS_TYPE_PHASE (PROCESS_TYPE_ID);
CREATE INDEX IDX_PROCESS_TYPE_PHASE_02 ON LEGAL.PROCESS_TYPE_PHASE (PROCESS_PHASE_ID);